version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server